modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="cgalaxy"
version="${file.jarVersion}"
displayName="CGalaxy"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="CGalaxy.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants"
description='''

'''
[[dependencies.cgalaxy]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.cgalaxy]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.cgalaxy]]
   modId="clib"
   mandatory=true
   versionRange="[2.0.0,)"
   ordering="BEFORE"
   side="BOTH"
