modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="MIT"

#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="workspace"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
# A display name for the mod
displayName="workspace" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="CLib.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
#authors="Love, Cheese and small house plants" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.workspace]] #optional
   # the modid of the dependency
   modId="forge" #mandatory
   # Does this dependency have to exist - if not, ordering below must be specified
   mandatory=true #mandatory
   # The version range of the dependency
   versionRange="[37,)" #mandatory
   # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
   ordering="NONE"
   # Side this dependency is applied on - BOTH, CLIENT or SERVER
   side="BOTH"
# Here's another dependency
[[dependencies.workspace]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[1.17.1,1.18)"
   ordering="NONE"
   side="BOTH"
